<a href="https://colab.research.google.com/github/MdImran2021/Day1/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Implementing Numpy using python programming**

In [ ]:
##Importing Libraries
import numpy as np
a = [1,2,3,4] #list
arr1 = np.array(a)
print(arr1)
b = [[1,2,3,4],[5,6,7,8]] #list2
arr2 = np.array(b)
print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
import sys

s = np.arange(10000)
print("Size of each element of numpy array in bytes",s.itemsize)
print("Size of whole array in bytes:",s.size*s.itemsize)

Size of each element of numpy array in bytes 8
Size of whole array in bytes: 80000


In [ ]:
import numpy as np
import time

a = np.arange(10000)
b = np.arange(10000)

start =time.time() #mark the start time

ab = [(a*b) for a,b in zip(a,b)]
end =time.time() #mark the end time
print("Total time taken:", end - start)

Total time taken: 0.0053539276123046875


In [ ]:
import numpy as np
arr3 = np.array([[1,2,3,4],[5,6,7,8]],ndmin =2) #2D np array
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
arr4 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr4.dtype)
print(arr4.ndim)
print(arr4.shape)
print(arr4.size)

int64
2
(2, 4)
8


In [ ]:
zero1 = np.zeros((2,2))
print(zero1)

[[0. 0.]
 [0. 0.]]


In [ ]:
c = np.arange(3,10,2)
print(type(c))

<class 'numpy.ndarray'>


In [ ]:
a = [1,2,3,4,5] 
b = np.array(a)
print(b)

[1 2 3 4 5]


In [ ]:
b[2]
b[4]

5

In [ ]:
b[-3]

3

In [ ]:
b[-4]

2

In [ ]:
b[0:2]

array([1, 2])

In [ ]:
b[0:5]

array([1, 2, 3, 4, 5])

In [ ]:
b[2]

3

In [ ]:
b[2] =5

In [ ]:
b[2]

5

In [ ]:
print(b)

[1 2 5 4 5]


In [ ]:
print(b[3, ])

4


In [ ]:
print(b[3: ])

[4 5]


In [ ]:
print(b[5: ])

[]


In [ ]:
print(b[:4])

[1 2 5 4]


In [ ]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
print(c[0])

[1 2 3 4 5]


In [ ]:
print(c[0][3])

4


 **Pandas Library Implementation**

In [1]:
import pandas as pd

dataset = pd.read_csv("/content/details.csv")

In [2]:
dataset.head(5)

ID     Name Year Department Section
0   1     Raja  4th       Mech       A
1   2    Mofiq  2nd      Civil       A
2   3    Muthu  3rd        CSE       B
3   4    Imran  3rd        CSE       B
4   5  Thowfiq  1st      Civil       C

In [3]:
dataset.tail(3)

ID     Name Year Department Section
2   3    Muthu  3rd        CSE       B
3   4    Imran  3rd        CSE       B
4   5  Thowfiq  1st      Civil       C

In [4]:

dataset.shape

(5, 5)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   ID          5 non-null      int64 
 1   Name        5 non-null      object
 2   Year        5 non-null      object
 3   Department  5 non-null      object
 4   Section     5 non-null      object
dtypes: int64(1), object(4)
memory usage: 328.0+ bytes


In [9]:

dataset1 = pd.read_html("https://en.wikipedia.org/wiki/Data_science")[0] 
dataset1.head()

0
0                                Part of a series on
1                    Machine learningand data mining
2  Problems Classification Clustering Regression ...
3  Supervised learning.mw-parser-output .nobold{f...
4  Clustering BIRCH CURE Hierarchical k-means Exp...

In [11]:
dataset.ID

0    1
1    2
2    3
3    4
4    5
Name: ID, dtype: int64

In [13]:
dataset.Name

0       Raja
1      Mofiq
2      Muthu
3      Imran
4    Thowfiq
Name: Name, dtype: object

In [14]:

dataset[['ID', 'Name', 'Department']]

ID     Name Department
0   1     Raja       Mech
1   2    Mofiq      Civil
2   3    Muthu        CSE
3   4    Imran        CSE
4   5  Thowfiq      Civil