<a href="https://colab.research.google.com/github/MdImran2021/Day1/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Implementing Numpy using python programming**

In [1]:
##Importing Libraries
import numpy as np
a = [1,2,3,4] #list
arr1 = np.array(a)
print(arr1)
b = [[1,2,3,4],[5,6,7,8]] #list2
arr2 = np.array(b)
print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [2]:
import numpy as np
import sys

s = np.arange(10000)
print("Size of each element of numpy array in bytes",s.itemsize)
print("Size of whole array in bytes:",s.size*s.itemsize)

Size of each element of numpy array in bytes 8
Size of whole array in bytes: 80000


In [3]:
import numpy as np
import time

a = np.arange(10000)
b = np.arange(10000)

start =time.time() #mark the start time

ab = [(a*b) for a,b in zip(a,b)]
end =time.time() #mark the end time
print("Total time taken:", end - start)

Total time taken: 0.0053539276123046875


In [4]:
import numpy as np
arr3 = np.array([[1,2,3,4],[5,6,7,8]],ndmin =2) #2D np array
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
arr4 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr4.dtype)
print(arr4.ndim)
print(arr4.shape)
print(arr4.size)

int64
2
(2, 4)
8


In [6]:
zero1 = np.zeros((2,2))
print(zero1)

[[0. 0.]
 [0. 0.]]


In [7]:
c = np.arange(3,10,2)
print(type(c))

<class 'numpy.ndarray'>


In [8]:
a = [1,2,3,4,5] 
b = np.array(a)
print(b)

[1 2 3 4 5]


In [9]:
b[2]
b[4]

5

In [10]:
b[-3]

3

In [11]:
b[-4]

2

In [12]:
b[0:2]

array([1, 2])

In [13]:
b[0:5]

array([1, 2, 3, 4, 5])

In [14]:
b[2]

3

In [15]:
b[2] =5

In [16]:
b[2]

5

In [17]:
print(b)

[1 2 5 4 5]


In [19]:
print(b[3, ])

4


In [20]:
print(b[3: ])

[4 5]


In [21]:
print(b[5: ])

[]


In [22]:
print(b[:4])

[1 2 5 4]


In [23]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [24]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
print(c[0])

[1 2 3 4 5]


In [26]:
print(c[0][3])

4
